### Convert tables to csv for easier import to postgres

In [2]:
import pandas as pd

This table includes data on google_businesses from google maps in california, the json format and unnecessary large data makes this hard to load. We will remove unnecessary columns an duplicated rows for easier loading.

In [3]:
google_path = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/meta-California.json"
df_g = pd.read_json(google_path,lines=True)
df_g.head(1)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.21529,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...

In [4]:
drop_columns = ['hours','state','relative_results','url','description','price','latitude','longitude']
df_g = df_g.drop(drop_columns, axis=1)

We can load our preview easier now with the large columns dropped

In [5]:
print(len(df_g))
df_g.head(10)

515961

,name,address,gmap_id,category,avg_rating,num_of_reviews,MISC
0,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,[Textile exporter],4.5,6,None
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,[Korean restaurant],4.4,18,"{'Service options': ['Takeout', 'Dine-in', 'De..."
2,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,[Fabric store],3.3,6,"{'Service options': ['In-store shopping'], 'Pa..."
3,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,[Fabric store],4.3,7,{'Service options': ['In-store pickup']}
4,Matrix International Textiles,"Matrix International Textiles, 1363 S Bonnie B...",0x80c2cf163db6bc89:0x219484e2edbcfa41,[Fabric store],3.5,6,{'Accessibility': ['Wheelchair accessible entr...
5,Vons Chicken,"Vons Chicken, 12740 La Mirada Blvd, La Mirada,...",0x80dd2b4c8555edb7:0xfc33d65c4bdbef42,[Restaurant],4.5,18,"{'Service options': ['Outdoor seating', 'Curbs..."
6,Black Tie Ski Rental Delivery of Mammoth,"Black Tie Ski Rental Delivery of Mammoth, 501 ...",0x80960c29f2e3bf29:0x4b291f0d275a5699,"[Ski rental service, Snowboard rental service]",5.0,34,{'Accessibility': ['Wheelchair accessible entr...
7,Angel-A Massage,"Angel-A Massage, 5329 Dewey Dr, Fair Oaks, CA ...",0x809adef58ae560bd:0x83412889e022ff70,"[Massage spa, Chiropractor, Massage, Massage t...",4.3,6,None
8,Dunn-Edwards Paints,"Dunn-Edwards Paints, 1850 Douglas Blvd #200, R...",0x809b1ff6d3a60c4d:0xdf08e68028807693,"[Paint store, Paint manufacturer]",4.7,26,"{'Service options': ['Curbside pickup', 'In-st..."
9,Elite Massage,"Elite Massage, 8121 Madison Ave, Fair Oaks, CA...",0x809ae0a7ce91433b:0xe4b44fbb8c35ba57,[Massage therapist],5.0,1,None

drop duplicated values based on gmap_id since this is our unique identifier

In [6]:
print(len(df_g[df_g.duplicated(['gmap_id'])]))
df_g.drop_duplicates(subset='gmap_id',inplace=True)

2827

In [7]:
#save to csv 
google_output = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/google_business.csv"
df_g.to_csv(google_output,index=False)

The inspections dataset includes information on health inspections at restuarants in california

In [9]:
inspections_path = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/Restaurant_and_Market_Health_Inspections.xlsx"
inspections_df = pd.read_excel(inspections_path)
inspections_df.head(5)

,serial_number,activity_date,facility_name,score,grade,service_code,service_description,employee_id,facility_address,facility_city,facility_id,facility_state,facility_zip,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id
0,DAJ00E07B,2017-12-29,HABITAT COFFEE SHOP,95,A,1,ROUTINE INSPECTION,EE0000923,3708 N EAGLE ROCK BLVD,LOS ANGELES,FA0170465,CA,90065,OW0178123,GLASSELL COFFEE SHOP LLC,RESTAURANT (0-30) SEATS MODERATE RISK,1631,HABITAT COFFEE SHOP,ACTIVE,PR0160774
1,DAQOKRFZB,2017-12-29,REILLY'S,92,A,1,ROUTINE INSPECTION,EE0000633,100 WORLD WAY # 120,LOS ANGELES,FA0244690,CA,90045,OW0208441,"AREAS SKYVIEW LAX JV, LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,REILLY'S,ACTIVE,PR0193026
2,DASJI4LUR,2017-12-29,STREET CHURROS,93,A,1,ROUTINE INSPECTION,EE0000835,6801 HOLLYWOOD BLVD # 253,LOS ANGELES,FA0224109,CA,90028,OW0228670,"STREETCHURROS, INC",RESTAURANT (0-30) SEATS LOW RISK,1630,STREET CHURROS,ACTIVE,PR0179282
3,DA40LU5AT,2017-12-29,TRINITI ECHO PARK,94,A,1,ROUTINE INSPECTION,EE0000923,1814 W SUNSET BLVD,LOS ANGELES,FA0252528,CA,90026-3227,OW0246287,AMERICAN HOSPITALITY,RESTAURANT (0-30) SEATS MODERATE RISK,1631,TRINITI ECHO PARK,ACTIVE,PR0201836
4,DAXV2RMYC,2017-12-29,POLLEN,94,A,1,ROUTINE INSPECTION,EE0000923,2100 ECHO PARK AVE,LOS ANGELES,FA0252789,CA,90026,OW0246479,"POLLEN AND PASTRY , LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,POLLEN,ACTIVE,PR0202148

In [10]:
print(len(inspections_df[inspections_df.duplicated(['serial_number'])]))

0

In [11]:
#drop uneeded columns 
inspections_df.drop(['program_name','program_status'],axis=1,inplace=True)

In [12]:
# save to csv
inspections_output = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/Inspections.csv"
inspections_df.to_csv(inspections_output,index=False)

The violations dataset includes more information on inspections in the inspections dataset

In [13]:
violations_path = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/Restaurant_and_Market_Health_Violations.csv"
violation_df = pd.read_csv(violations_path)

In [14]:
violation_df.head(5)

,serial_number,activity_date,facility_name,violation_code,violation_description,violation_status,points,grade,facility_address,facility_city,...,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,service_code,service_description,row_id
0,DA08R0TCU,03/30/2018 12:00:00 AM,KRUANG TEDD,F030,# 30. Food properly stored; food storage conta...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF030
1,DA08R0TCU,03/30/2018 12:00:00 AM,KRUANG TEDD,F027,# 27. Food separated and protected,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF027
2,DA08R0TCU,03/30/2018 12:00:00 AM,KRUANG TEDD,F035,# 35. Equipment/Utensils - approved; installed...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF035
3,DA08R0TCU,03/30/2018 12:00:00 AM,KRUANG TEDD,F033,# 33. Nonfood-contact surfaces clean and in go...,OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF033
4,DA08R0TCU,03/30/2018 12:00:00 AM,KRUANG TEDD,F029,"# 29. Toxic substances properly identified, st...",OUT OF COMPLIANCE,1,A,5151 HOLLYWOOD BLVD,LOS ANGELES,...,5151 HOLLYWOOD LLC,RESTAURANT (31-60) SEATS HIGH RISK,1635,KRUANG TEDD,ACTIVE,PR0031205,92,1,ROUTINE INSPECTION,DA08R0TCUF029

In [15]:
print(len(violation_df[violation_df.duplicated(['serial_number','violation_code'])]))
violation_df.drop(['program_name','program_status'],axis=1,inplace=True)

0

In [16]:
violation_output = "C:/Users/cbrun/OneDrive/Documents/Inspection_Project/Violations.csv"
violation_df.to_csv(violation_output,index=False)